# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gsmoPbOp9VLxbgdtMWDfNVPdFrdjNqLe

## Generate an Artistic Poster

We will use the `diffusers` library and a pre-trained Stable Diffusion model to generate an artistic poster from a text prompt.

## Generative Artistic Poster with Matplotlib

This section generates an artistic poster using `matplotlib` based on the following constraints:
- No external data.
- Random color palette.
- 6-10 layered organic 'blob' shapes.
- Parameterized wobble and radius for the blobs.
"""

import matplotlib.pyplot as plt
import numpy as np
import random

"""### (a) Color Palette Function

This function generates a list of random, vibrant colors. We'll generate random RGB tuples to ensure a diverse palette without relying on predefined sets.
"""

def generate_random_palette(num_colors, blend_with_white=0.3):
    """
    Generates a list of highly diverse, vibrant, and rich RGB color tuples,
    with an adjustable blend with white to preserve vibrant color diversity.
    """
    palette = []
    for _ in range(num_colors):
        # Generate highly diverse base colors across the full spectrum
        r = random.uniform(0.0, 1.0)
        g = random.uniform(0.0, 1.0)
        b = random.uniform(0.0, 1.0)

        # Ensure we don't get purely dark/grayish muddy colors
        max_val = max(r, g, b)
        if max_val < 0.5:
            r, g, b = r / max_val * 0.7, g / max_val * 0.7, b / max_val * 0.7

        # Blend with white (lower default blend factor yields more diverse and saturated colors)
        r_vibrant = r * (1 - blend_with_white) + 1.0 * blend_with_white
        g_vibrant = g * (1 - blend_with_white) + 1.0 * blend_with_white
        b_vibrant = b * (1 - blend_with_white) + 1.0 * blend_with_white

        palette.append((r_vibrant, g_vibrant, b_vibrant))
    return palette

"""### (b) Blob Generator Function

This function creates the coordinates for a single organic 'blob' shape. It starts with a circle and then adds random perturbations (wobble) to its radius at different angles to create an organic, irregular form. The center of the blob is also parameterized to allow for flexible positioning.
"""

def generate_blob_coords(radius, wobble_factor, center_x, center_y, shape_type="Circle", num_points=120):
    """
    Generates (x, y) coordinates for an organic blob starting from a base shape
    and perturbing it dynamically.
    """
    theta = np.linspace(0, 2 * np.pi, num_points, endpoint=False)

    # Define the base radial structure based on the selected shape
    if shape_type == "Heart":
        x_base = 16 * np.sin(theta)**3
        y_base = 13 * np.cos(theta) - 5 * np.cos(2*theta) - 2 * np.cos(3*theta) - np.cos(4*theta)
        norm = np.sqrt(x_base**2 + y_base**2)
        max_norm = np.max(norm) if np.max(norm) > 0 else 1.0
        x_base = (x_base / max_norm) * radius
        y_base = (y_base / max_norm) * radius + (0.1 * radius)
    elif shape_type == "Rectangle":
        r_base = radius / np.maximum(np.abs(np.cos(theta)), np.abs(np.sin(theta)))
        x_base = r_base * np.cos(theta)
        y_base = r_base * np.sin(theta)
    elif shape_type == "Star":
        star_pattern = 1.0 + 0.5 * np.sin(5 * theta)
        x_base = radius * star_pattern * np.cos(theta)
        y_base = radius * star_pattern * np.sin(theta)
    elif shape_type == "Triangle":
        r_base = radius / (np.cos(theta - (2 * np.pi / 3) * np.floor((3 * theta + np.pi) / (2 * np.pi))))
        r_base = np.clip(r_base, 0, radius * 2.0)
        x_base = r_base * np.cos(theta)
        y_base = r_base * np.sin(theta)
    elif shape_type == "Shield":
        r_base = radius * (1.0 - 0.3 * np.abs(np.sin(theta)) * (theta > np.pi))
        x_base = r_base * np.cos(theta)
        y_base = r_base * np.sin(theta)
    elif shape_type == "Gun":
        # Parametric approximate pistol shape silhouette
        raw_x = np.cos(theta)
        raw_y = np.sin(theta)
        # Extend left/up for the barrel and down for the grip
        for i, t in enumerate(theta):
            if 0 <= t < np.pi/2:
                raw_x[i] *= 1.8  # barrel length
                raw_y[i] *= 0.6  # barrel height
            elif np.pi/2 <= t < np.pi:
                raw_x[i] *= 0.8
                raw_y[i] *= 0.8
            elif np.pi <= t < 1.5 * np.pi:
                raw_x[i] *= 0.7  # grip width
                raw_y[i] *= 1.6  # grip length
        norm = np.sqrt(raw_x**2 + raw_y**2)
        max_norm = np.max(norm) if np.max(norm) > 0 else 1.0
        x_base = (raw_x / max_norm) * radius
        y_base = (raw_y / max_norm) * radius
    elif shape_type == "Trump":
        # Fun approximation profile: face + prominent forward hair tuft
        raw_x = np.cos(theta)
        raw_y = np.sin(theta)
        for i, t in enumerate(theta):
            if 0 <= t < np.pi/3:
                raw_x[i] *= 1.7  # Front hair sweep / coiffure
                raw_y[i] *= 1.4
            elif np.pi/3 <= t < np.pi/2:
                raw_x[i] *= 1.3
            elif 1.5*np.pi <= t < 2*np.pi:
                raw_x[i] *= 1.2  # Forehead and nose projection profile
        norm = np.sqrt(raw_x**2 + raw_y**2)
        max_norm = np.max(norm) if np.max(norm) > 0 else 1.0
        x_base = (raw_x / max_norm) * radius
        y_base = (raw_y / max_norm) * radius
    else: # Default: Circle
        x_base = radius * np.cos(theta)
        y_base = radius * np.sin(theta)

    # Add random perturbations (wobble) to the base coordinates
    perturb_x = np.random.uniform(-wobble_factor * radius, wobble_factor * radius, num_points)
    perturb_y = np.random.uniform(-wobble_factor * radius, wobble_factor * radius, num_points)

    x_coords = x_base + perturb_x + center_x
    y_coords = y_base + perturb_y + center_y

    return x_coords, y_coords

"""### (c) Main Drawing Function `generate_poster()` with Parameters

This function orchestrates the creation of the entire poster. It combines the color palette and blob generator to draw multiple layered shapes on a Matplotlib figure. Parameters allow detailed control over the number of layers, their size, wobble, transparency, and the overall color scheme. A `seed` is included for reproducibility.
"""

def generate_poster(
    seed=None,
    n_layers=8,
    radius_range=(0.1, 0.4),
    wobble_range=(0.1, 0.3),
    palette_size=5,
    blend_with_white=0.15,
    figure_size=(10, 10),
    base_alpha=0.7,
    title_text="",
    title_fontsize=62
):
    """
    Creates and displays a generative artistic poster with a background color
    guaranteed to be highly distinct from the organic patterns and title.
    """
    if seed is not None:
        random.seed(seed)
        np.random.seed(seed)

    n_layers = max(6, min(10, n_layers))

    fig, ax = plt.subplots(figsize=figure_size)
    ax.set_aspect('equal', adjustable='box')

    ax.set_xlim(-0.1, 1.1)
    ax.set_ylim(-0.1, 1.1)
    ax.axis('off')

    # Generate a distinct base palette for the patterns (blobs)
    palette = generate_random_palette(palette_size, blend_with_white=blend_with_white)

    # Generate a background color that is completely distinct from any blob color
    # We loop until we find a color with a high Euclidean distance from all palette colors
    while True:
        bg_color = generate_random_palette(1, blend_with_white=0.1)[0]
        # Measure min distance to any color in the blob palette
        min_dist = min(np.linalg.norm(np.array(bg_color) - np.array(c)) for c in palette)
        if min_dist > 0.35: # Ensure strong color distinction
            break

    # Set figure background color dynamically
    fig.patch.set_facecolor(bg_color)
    ax.set_facecolor(bg_color)

    # Determine high-contrast title color based on background brightness (luminance)
    bg_luminance = 0.299 * bg_color[0] + 0.587 * bg_color[1] + 0.114 * bg_color[2]
    title_color = '#FFFFFF' if bg_luminance < 0.5 else '#0A0A0A'

    for i in range(n_layers):
        radius = random.uniform(radius_range[0], radius_range[1])
        wobble_factor = random.uniform(wobble_range[0], wobble_range[1])
        center_x = random.uniform(0, 1)
        center_y = random.uniform(0, 1)
        color = random.choice(palette)
        current_alpha = random.uniform(base_alpha * 0.8, min(1.0, base_alpha * 1.2))

        x_coords, y_coords = generate_blob_coords(radius, wobble_factor, center_x, center_y)

        # Use a high contrast border overlay for maximum pop
        ax.fill(x_coords, y_coords, facecolor=color, edgecolor='#111111', linewidth=1.5, alpha=current_alpha, zorder=i)

    if title_text:
        ax.text(0.05, 1.05, title_text, transform=ax.transAxes, fontsize=title_fontsize,
                color=title_color, ha='left', va='top', zorder=n_layers + 1)

    plt.tight_layout()
    return fig, ax

# --- Demo of the poster generation with diverse colors and distinct background ---
fig, ax = generate_poster(
    seed=None,
    n_layers=8,
    radius_range=(0.1, 0.45),
    wobble_range=(0.1, 0.25),
    palette_size=8,
    blend_with_white=0.15,
    figure_size=(10, 10),
    base_alpha=0.75,
    title_text="ART WEEK",
    title_fontsize=62
)
plt.show()

"""### (d) Tips to Adjust Aesthetics

To customize the look of your generative poster, experiment with the parameters of the `generate_poster` function:

*   **`seed`**: Provide an integer value for `seed` to get the same poster design every time you run the code. Remove or set to `None` for a new random design.
*   **`n_layers`**: Changes the number of blob shapes. A higher number (up to 10) increases density, while a lower number (down to 6) makes the poster sparser.
*   **`radius_range`**: A tuple `(min_radius, max_radius)` that controls the size range of the blobs. Increase `max_radius` for larger shapes, decrease `min_radius` for smaller ones. A narrower range makes blob sizes more uniform.
*   **`wobble_range`**: A tuple `(min_wobble, max_wobble)` that adjusts the organic irregularity of the blob edges. Values closer to 0 make blobs more circular/smoother, while higher values (e.g., up to `0.5`) create more distorted, abstract, or spiky shapes.
*   **`palette_size`**: Determines how many distinct colors are generated for the random palette. A larger number provides more color variety.
*   **`blend_with_white`**: Controls how 'pastel' the colors are. A value of `0.0` will result in more vibrant, pure colors, while a value closer to `1.0` will make the colors very light, almost white.
*   **`figure_size`**: Changes the overall dimensions of the poster image.
*   **`base_alpha`**: Controls the base transparency of the blobs. Values closer to 0.0 make them more transparent, allowing underlying blobs to show through more. Values closer to 1.0 make them more opaque. Each blob's actual alpha will slightly vary around this base for a layered effect.
*   **`title_text`**: The text displayed in the top-left corner of the poster. Set to an empty string `""` to remove the text.
*   **`title_fontsize`**: The font size of the title text. Adjust as needed for visibility.

Feel free to re-run the `generate_poster` cell with different parameter values to see how they affect the output!

### Interactive Poster with Matplotlib Widgets

Run the cell below to load the interactive canvas. You can use the sliders on the left/bottom to adjust the configurations, and click anywhere inside the main canvas area to dynamically add new organic blobs!
"""

import os
import urllib.request
import matplotlib.pyplot as plt
import numpy as np
import random
import ipywidgets as widgets
from IPython.display import display, clear_output
import warnings
from matplotlib import font_manager

# Create a local directory for our customized fonts
os.makedirs("custom_fonts", exist_ok=True)

# Suppress any remaining fallback warnings
warnings.filterwarnings("ignore", category=UserWarning, module="matplotlib")

def generate_random_palette(num_colors, blend_with_white=0.3):
    """
    Generates a list of highly diverse, vibrant, and rich RGB color tuples,
    with an adjustable blend with white to preserve vibrant color diversity.
    """
    palette = []
    for _ in range(num_colors):
        # Generate highly diverse base colors across the full spectrum
        r = random.uniform(0.0, 1.0)
        g = random.uniform(0.0, 1.0)
        b = random.uniform(0.0, 1.0)

        # Ensure we don't get purely dark/grayish muddy colors
        max_val = max(r, g, b)
        if max_val < 0.5:
            r, g, b = r / max_val * 0.7, g / max_val * 0.7, b / max_val * 0.7

        # Blend with white (lower default blend factor yields more diverse and saturated colors)
        r_vibrant = r * (1 - blend_with_white) + 1.0 * blend_with_white
        g_vibrant = g * (1 - blend_with_white) + 1.0 * blend_with_white
        b_vibrant = b * (1 - blend_with_white) + 1.0 * blend_with_white

        palette.append((r_vibrant, g_vibrant, b_vibrant))
    return palette

def generate_blob_coords(radius, wobble_factor, center_x, center_y, shape_type="Circle", num_points=120):
    """
    Generates (x, y) coordinates for an organic blob starting from a base shape
    and perturbing it dynamically.
    """
    theta = np.linspace(0, 2 * np.pi, num_points, endpoint=False)

    # Define the base radial structure based on the selected shape
    if shape_type == "Heart":
        x_base = 16 * np.sin(theta)**3
        y_base = 13 * np.cos(theta) - 5 * np.cos(2*theta) - 2 * np.cos(3*theta) - np.cos(4*theta)
        norm = np.sqrt(x_base**2 + y_base**2)
        max_norm = np.max(norm) if np.max(norm) > 0 else 1.0
        x_base = (x_base / max_norm) * radius
        y_base = (y_base / max_norm) * radius + (0.1 * radius)
    elif shape_type == "Rectangle":
        r_base = radius / np.maximum(np.abs(np.cos(theta)), np.abs(np.sin(theta)))
        x_base = r_base * np.cos(theta)
        y_base = r_base * np.sin(theta)
    elif shape_type == "Star":
        star_pattern = 1.0 + 0.5 * np.sin(5 * theta)
        x_base = radius * star_pattern * np.cos(theta)
        y_base = radius * star_pattern * np.sin(theta)
    elif shape_type == "Triangle":
        r_base = radius / (np.cos(theta - (2 * np.pi / 3) * np.floor((3 * theta + np.pi) / (2 * np.pi))))
        r_base = np.clip(r_base, 0, radius * 2.0)
        x_base = r_base * np.cos(theta)
        y_base = r_base * np.sin(theta)
    elif shape_type == "Shield":
        r_base = radius * (1.0 - 0.3 * np.abs(np.sin(theta)) * (theta > np.pi))
        x_base = r_base * np.cos(theta)
        y_base = r_base * np.sin(theta)
    elif shape_type == "Gun":
        # Parametric approximate pistol shape silhouette
        raw_x = np.cos(theta)
        raw_y = np.sin(theta)
        # Extend left/up for the barrel and down for the grip
        for i, t in enumerate(theta):
            if 0 <= t < np.pi/2:
                raw_x[i] *= 1.8  # barrel length
                raw_y[i] *= 0.6  # barrel height
            elif np.pi/2 <= t < np.pi:
                raw_x[i] *= 0.8
                raw_y[i] *= 0.8
            elif np.pi <= t < 1.5 * np.pi:
                raw_x[i] *= 0.7  # grip width
                raw_y[i] *= 1.6  # grip length
        norm = np.sqrt(raw_x**2 + raw_y**2)
        max_norm = np.max(norm) if np.max(norm) > 0 else 1.0
        x_base = (raw_x / max_norm) * radius
        y_base = (raw_y / max_norm) * radius
    elif shape_type == "Trump":
        # Fun approximation profile: face + prominent forward hair tuft
        raw_x = np.cos(theta)
        raw_y = np.sin(theta)
        for i, t in enumerate(theta):
            if 0 <= t < np.pi/3:
                raw_x[i] *= 1.7  # Front hair sweep / coiffure
                raw_y[i] *= 1.4
            elif np.pi/3 <= t < np.pi/2:
                raw_x[i] *= 1.3
            elif 1.5*np.pi <= t < 2*np.pi:
                raw_x[i] *= 1.2  # Forehead and nose projection profile
        norm = np.sqrt(raw_x**2 + raw_y**2)
        max_norm = np.max(norm) if np.max(norm) > 0 else 1.0
        x_base = (raw_x / max_norm) * radius
        y_base = (raw_y / max_norm) * radius
    else: # Default: Circle
        x_base = radius * np.cos(theta)
        y_base = radius * np.sin(theta)

    # Add random perturbations (wobble) to the base coordinates
    perturb_x = np.random.uniform(-wobble_factor * radius, wobble_factor * radius, num_points)
    perturb_y = np.random.uniform(-wobble_factor * radius, wobble_factor * radius, num_points)

    x_coords = x_base + perturb_x + center_x
    y_coords = y_base + perturb_y + center_y

    return x_coords, y_coords

class InteractivePosterColab:
    def __init__(self):
        self.n_layers = 7
        self.max_wobble = 0.25
        self.max_radius = 0.45
        self.palette_size = 7
        self.blend_with_white = 0.15
        self.base_alpha = 0.75
        self.bg_color = (0.96, 0.96, 0.96)
        self.title_color = '#111111'
        self.title_fontsize = 32

        # Mapped lists of shapes, titles and font families
        self.shapes_list = ["Circle", "Heart", "Rectangle", "Star", "Triangle", "Shield", "Gun", "Trump"]
        self.selected_shape = self.shapes_list[0]
        self.titles_list = ["ART WEEK", "CREATIVE", "MODERNISM", "EXHIBIT", "GALLERY", "GEOMETRIC"]
        self.title_text = self.titles_list[0]
        # Use generic font families as specific font downloads are removed
        self.fonts_list = ["sans-serif", "serif", "monospace"]
        self.title_fontfamily = self.fonts_list[0]

        self.custom_blobs = []

        self.slider_layers = widgets.IntSlider(value=self.n_layers, min=3, max=15, step=1, description='Layers:')
        self.slider_wobble = widgets.FloatSlider(value=self.max_wobble, min=0.0, max=0.5, step=0.05, description='Wobble:')
        self.slider_radius = widgets.FloatSlider(value=self.max_radius, min=0.1, max=0.6, step=0.05, description='Blob Size:')
        self.slider_palette = widgets.IntSlider(value=self.palette_size, min=2, max=12, step=1, description='Palette Size:')
        self.slider_params = widgets.FloatSlider(value=self.base_alpha, min=0.1, max=1.0, step=0.05, description='parameters:')

        # Slider for changing the blob structure shape
        self.slider_shape = widgets.SelectionSlider(options=self.shapes_list, value=self.selected_shape, description='Shape:')
        # Slider for changing the title text
        self.slider_title = widgets.IntSlider(value=0, min=0, max=len(self.titles_list) - 1, step=1, description='Title Option:')
        # Slider for changing the title font size
        self.slider_font = widgets.IntSlider(value=self.title_fontsize, min=12, max=72, step=2, description='Font Size:')

        self.input_title = widgets.Text(value=self.title_text, description='Title Text:')
        self.btn_regen = widgets.Button(description='Regenerate Base')

        self.out = widgets.Output()

        self.slider_layers.observe(self.on_value_change, names='value')
        self.slider_wobble.observe(self.on_value_change, names='value')
        self.slider_radius.observe(self.on_value_change, names='value')
        self.slider_palette.observe(self.on_value_change, names='value')
        self.slider_params.observe(self.on_value_change, names='value')
        self.slider_shape.observe(self.on_shape_change, names='value')
        self.slider_title.observe(self.on_slider_title_change, names='value')
        self.slider_font.observe(self.on_font_change, names='value')
        self.input_title.observe(self.on_title_change, names='value')
        self.btn_regen.on_click(self.on_regen_click)

        self.regenerate_base_blobs()

        controls = widgets.VBox([
            self.slider_layers,
            self.slider_wobble,
            self.slider_radius,
            self.slider_palette,
            self.slider_params,
            self.slider_shape,
            self.slider_title,
            self.slider_font,
            self.input_title,
            self.btn_regen
        ])

        display(widgets.HBox([controls, self.out]))
        self.draw_poster()

    def regenerate_base_blobs(self):
        self.palette = generate_random_palette(int(self.palette_size), blend_with_white=self.blend_with_white)

        while True:
            bg_cand = generate_random_palette(1, blend_with_white=0.1)[0]
            min_dist = min(np.linalg.norm(np.array(bg_cand) - np.array(c)) for c in self.palette)
            if min_dist > 0.35:
                self.bg_color = bg_cand
                break

        bg_luminance = 0.299 * self.bg_color[0] + 0.587 * self.bg_color[1] + 0.114 * self.bg_color[2]
        self.title_color = '#FFFFFF' if bg_luminance < 0.5 else '#0A0A0A'

        self.base_blobs = []
        for i in range(int(self.n_layers)):
            radius = random.uniform(self.max_radius * 0.4, self.max_radius)
            wobble_factor = random.uniform(0.05, self.max_wobble)
            center_x = random.uniform(0.1, 0.9)
            center_y = random.uniform(0.1, 0.9)
            color = random.choice(self.palette)
            alpha = random.uniform(self.base_alpha * 0.8, min(1.0, self.base_alpha * 1.2))

            self.base_blobs.append({
                'radius': radius,
                'wobble': wobble_factor,
                'cx': center_x,
                'cy': center_y,
                'color': color,
                'alpha': alpha
            })

    def draw_poster(self):
        with self.out:
            clear_output(wait=True)
            fig, ax = plt.subplots(figsize=(8, 8))
            ax.set_aspect('equal', adjustable='box')
            ax.set_xlim(-0.1, 1.1)
            ax.set_ylim(-0.1, 1.1)
            ax.axis('off')

            fig.patch.set_facecolor(self.bg_color)
            ax.set_facecolor(self.bg_color)

            def draw_3d_blob(blob, layer_index):
                x_coords, y_coords = generate_blob_coords(
                    blob['radius'], blob['wobble'], blob['cx'], blob['cy'], shape_type=self.selected_shape
                )

                z_base = (layer_index + 1) * 3

                shadow_offset_x = 0.015
                shadow_offset_y = -0.015
                ax.fill(
                    x_coords + shadow_offset_x,
                    y_coords + shadow_offset_y,
                    facecolor='#111111',
                    edgecolor='none',
                    alpha=0.18 * blob['alpha'],
                    zorder=z_base
                )

                ax.fill(
                    x_coords,
                    y_coords,
                    facecolor='#222222',
                    edgecolor='none',
                    alpha=blob['alpha'],
                    zorder=z_base + 1
                )

                body_offset_x = -0.005
                body_offset_y = 0.005
                ax.fill(
                    x_coords + body_offset_x,
                    y_coords + body_offset_y,
                    facecolor=blob['color'],
                    edgecolor=blob['color'],
                    linewidth=1.0,
                    alpha=blob['alpha'],
                    zorder=z_base + 2
                )

            for i, blob in enumerate(self.base_blobs):
                draw_3d_blob(blob, i)

            for i, blob in enumerate(self.custom_blobs):
                draw_3d_blob(blob, len(self.base_blobs) + i)

            # Draw the title on top of all blobs (zorder=1000)
            if self.title_text:
                ax.text(0.05, 0.95, self.title_text, transform=ax.transAxes,
                         fontsize=self.title_fontsize, family=self.title_fontfamily,
                         color=self.title_color, ha='left', va='top', zorder=1000)

            plt.show()

    def on_value_change(self, change):
        self.n_layers = self.slider_layers.value
        self.max_wobble = self.slider_wobble.value
        self.max_radius = self.slider_radius.value
        self.palette_size = self.slider_palette.value
        self.base_alpha = self.slider_params.value
        self.regenerate_base_blobs()
        self.draw_poster()

    def on_shape_change(self, change):
        self.selected_shape = self.slider_shape.value
        self.draw_poster()

    def on_slider_title_change(self, change):
        index = self.slider_title.value
        self.title_text = self.titles_list[index]
        self.input_title.value = self.title_text
        self.draw_poster()

    def on_font_change(self, change):
        self.title_fontsize = self.slider_font.value
        self.draw_poster()

    def on_title_change(self, change):
        self.title_text = self.input_title.value
        self.draw_poster()

    def on_regen_click(self, button):
        self.regenerate_base_blobs()
        self.draw_poster()

app = InteractivePosterColab()